version: "3.8"

services:
  kafka-0:
    container_name: kafka-0
    image: bitnami/kafka:3.7.0
    ports:
      - "${KAFKA_0_PORT}:${KAFKA_0_PORT}"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes  # Data is transmitted without encryption (not recommended for production)

      # KRAFT config
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:${KAFKA_CONTROLLER_PORT},1@kafka-1:${KAFKA_CONTROLLER_PORT},2@kafka-2:${KAFKA_CONTROLLER_PORT}
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PLAINTEXT_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT},EXTERNAL://:${KAFKA_0_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:${KAFKA_PLAINTEXT_PORT},EXTERNAL://${KAFKA_0_HOST}:${KAFKA_0_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - SENTRY_DSN=${SENTRY_DSN}
    volumes:
      - ${INFRA_STORAGE}/kafka/kafka_0_data:/bitnami/kafka

  kafka-1:
    container_name: kafka-1
    image: bitnami/kafka:3.7.0
    ports:
      - "${KAFKA_1_PORT}:${KAFKA_1_PORT}"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:${KAFKA_CONTROLLER_PORT},1@kafka-1:${KAFKA_CONTROLLER_PORT},2@kafka-2:${KAFKA_CONTROLLER_PORT}
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PLAINTEXT_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT},EXTERNAL://:${KAFKA_1_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:${KAFKA_PLAINTEXT_PORT},EXTERNAL://${KAFKA_1_HOST}:${KAFKA_1_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - ${INFRA_STORAGE}/kafka/kafka_1_data:/bitnami/kafka

  kafka-2:
    container_name: kafka-2
    image: bitnami/kafka:3.7.0
    ports:
      - "${KAFKA_2_PORT}:${KAFKA_2_PORT}"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:${KAFKA_CONTROLLER_PORT},1@kafka-1:${KAFKA_CONTROLLER_PORT},2@kafka-2:${KAFKA_CONTROLLER_PORT}
      - KAFKA_KRAFT_CLUSTER_ID=${KAFKA_KRAFT_CLUSTER_ID}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PLAINTEXT_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT},EXTERNAL://:${KAFKA_2_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:${KAFKA_PLAINTEXT_PORT},EXTERNAL://${KAFKA_2_HOST}:${KAFKA_2_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - ${INFRA_STORAGE}/kafka/kafka_2_data:/bitnami/kafka

  ui:
    container_name: ui
    image: provectuslabs/kafka-ui:v0.7.0
    ports:
      - "${KAFKA_UI_PORT}:${KAFKA_UI_PORT}"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:${KAFKA_PLAINTEXT_PORT}
      - KAFKA_CLUSTERS_0_NAME=kraft

volumes:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data:
